folder_location:
preprocessing:
  zoom:
   is_on: True
   zoom_factor:
  brightness:
   is_on: True
   brightness_factor:
  translation:
   is_on: True
   translation_coord:
  rotation:
   is_on: True
   rotation_degree:
  shearing:
   is_on: True
   shear_pixel_displacement:
